# TCL File Generated by Component Editor 18.1
# Tue Jan 21 11:19:25 CET 2020
# DO NOT MODIFY


# 
# adc_ltc2308 "adc_ltc2308" v1.0
# Richard 2020.01.21.11:19:25
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module adc_ltc2308
# 
set_module_property DESCRIPTION ""
set_module_property NAME adc_ltc2308
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Qsys Component"
set_module_property AUTHOR Richard
set_module_property DISPLAY_NAME adc_ltc2308
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL adc_ltc2308_fifo
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file adc_data_fifo.v VERILOG PATH ADC_LTC2308_FIFO/adc_data_fifo.v
add_fileset_file adc_ltc2308.v VERILOG PATH ADC_LTC2308_FIFO/adc_ltc2308.v
add_fileset_file adc_ltc2308_fifo.v VERILOG PATH ADC_LTC2308_FIFO/adc_ltc2308_fifo.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock_sink
set_interface_property slave associatedReset reset_n
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_chipselect_n chipselect_n Input 1
add_interface_port slave slave_read_n read_n Input 1
add_interface_port slave slave_readdata readdata Output 16
add_interface_port slave slave_wrtie_n beginbursttransfer Input 1
add_interface_port slave slave_addr beginbursttransfer Input 1
add_interface_port slave slave_wriredata writebyteenable_n Input 16
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink slave_clk clk Input 1


# 
# connection point clock_adc
# 
add_interface clock_adc clock end
set_interface_property clock_adc clockRate 0
set_interface_property clock_adc ENABLED true
set_interface_property clock_adc EXPORT_OF ""
set_interface_property clock_adc PORT_NAME_MAP ""
set_interface_property clock_adc CMSIS_SVD_VARIABLES ""
set_interface_property clock_adc SVD_ADDRESS_GROUP ""

add_interface_port clock_adc adc_clk clk Input 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock_sink
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n slave_reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset_n
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end ADC_CONVST writeresponsevalid_n Output 1
add_interface_port conduit_end ADC_SCK writeresponsevalid_n Output 1
add_interface_port conduit_end ADC_SDI writeresponsevalid_n Output 1
add_interface_port conduit_end ADC_SDO beginbursttransfer Input 1

